name: Docker release

on:
  push:
    branches:
      - master
    paths:
      # Keep this in line with .dockerignore
      - bin/scripts/docker-entrypoint.sh
      - bin/scripts/name_parser/Fontname*.py
      - src/glyphs/**
      - .dockerignore
      - Dockerfile
      - font-patcher
  workflow_dispatch:

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ryanoasis' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Docker Meta provides automatic, standard tagging
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: nerdfonts/patcher
          flavor: latest=auto

        # QEMU allows us to build container images for multiple architectures (amd64, ARM etc...)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

        # Docker Buildx provides Buildkit support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
