name: Docker release

on:
  push:
    branches:
      - master
    paths:
      # Keep this in line with .dockerignore
      - bin/scripts/docker-entrypoint.sh
      - bin/scripts/name_parser/Fontname*.py
      - src/glyphs/**
      - .dockerignore
      - Dockerfile
      - font-patcher

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ryanoasis' }}
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t nerdfonts/patcher .
      - name: Push image
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PAT }}
          docker push nerdfonts/patcher
