# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Workflow to build and install dependencies
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      RELEASE_TAG_VERSION: 2.2.0-RC
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      SANITY_TEST: ${{ secrets.SANITY_TEST }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '1'

      # Install and setup Dependencies
      - name: Setup core dependencies
        run: |
          sudo apt update -y -q
          sudo apt install software-properties-common -y -q
          sudo apt update -y -q
          sudo apt install fontforge -y -q
          sudo apt install python3-fontforge -y -q

      - name: Setup additional dependencies
        run: |
          pip install fonttools --quiet

      - name: Build FreeType from source
        run: |
          wget http://downloads.sourceforge.net/project/freetype/freetype2/2.7/freetype-2.7.tar.gz --quiet
          tar -zxf freetype-2.7.tar.gz
          cd freetype-2.7
          ./configure
          make --quiet
          sudo make install --quiet

      - name: Build Harfbuzz from source
        run: |
          wget http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.3.4.tar.bz2 --quiet
          tar -xjf harfbuzz-1.3.4.tar.bz2
          cd harfbuzz-1.3.4
          ./configure
          make --quiet
          sudo make install --quiet

      - name: Verify setup
        run: |
          fontforge --version
          fontforge --version 2>&1 | grep libfontforge | awk '{print $NF}'

      - name: Patcher test run
        run: |
          fontforge --script ./font-patcher src/unpatched-fonts/Hasklig/Regular/Hasklig-Regular.otf --complete --quiet --no-progressbars

      - name: Bump version and standardize the readme files
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./version-bump.sh "$RELEASE_VERSION"
          ./standardize-and-complete-readmes.sh

      - name: Patch all the fonts (just ShareTechMono for now)
        # let's test just on font family for now to prove it out
        # once proven we'll remove the font name and the hardcoded release and use the "release" script
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./gotta-patch-em-all-font-patcher\!.sh "ShareTechMono"

      - name: Generate fontconfig and casks
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./generate-fontconfig.sh
          ./generate-casks.sh

      - name: Archive font package zip files and upload for release (just ShareTechMono for now)
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./archive-fonts.sh "ShareTechMono"
          GITHUB_TOKEN=$GITHUB_TOKEN ./upload-archives-lab.sh $RELEASE_TAG_VERSION
